# Site settings
title: Curate
author: Kim Hamper
description: ""
baseurl: ""
url: "http://kalongthewires.github.io"
github_username:  kalongthewires

highlighter: rouge
permalink: none

# Build settings
markdown: kramdown