# Site settings
title: Curate
author: Kim Hamper
description: "A small curation site"
baseurl: ""
url: "http://kalongthewires.github.io"
github_username:  kalongthewires

highlighter: rouge
permalink: none

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap # Enable automatic site-map generation on Github
  - jemoji # Enable emoji on Github - cheat sheet here: http://www.emoji-cheat-sheet.com/